g43exercise/urls.py
from django.conf.urls import patterns, url
from g43exercise import views
from django.conf.urls.static import static
from django.conf import settings

# Create your urls patterns here.
urlpatterns = patterns('',
	# The index page /g43exercise
	url(r'^$', views.index, name='index'),
	# The article detail page 
	# ex. /g43exercise/1
	url(r'^(?P<article_id>\d+)/$', views.detail, name='detail'),
	# Any media elements found in the media directory
	# ex. /g43exercise/media/heroes/filename.jpg
	url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
		'document_root': settings.MEDIA_ROOT,
	}, name='media'),
	# Any static elements found in the static directory
	# ex. /g43exercise/static/css/style.css
	url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
		'document_root': settings.STATIC_ROOT,
	}),
)

wireframe/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'wireframe.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	url(r'^g43exercise/', include('g43exercise.urls', namespace="g43")),
    url(r'^admin/', include(admin.site.urls)),
)

g43exercise/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings

import datetime

# Create your models here.
class Article(models.Model):
	# The barebones of a published Article. Includes a secondary image option
	article_id = models.AutoField(primary_key=True)
	title = models.CharField(max_length=200)
	author = models.CharField(max_length=50)
	pub_date = models.DateTimeField('date published')
	category = models.CharField(max_length=50)
	hero_image = models.ImageField(upload_to='heroes/', default='heroes/default-hero.jpg')
	optional_image = models.ImageField(upload_to='extra/', default='extra/default-hero.jpg')
	body_text = models.TextField(max_length=5000)
	def __str__(self):
		return self.title + ' by ' + self.author
	

g43exercise/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.utils import timezone

from g43exercise.models import Article

# Create your views here.
# Create the context list for all present/past dated articles
all_articles = Article.objects.filter(
				pub_date__lte=timezone.now()
				).order_by('pub_date')
def index(request):
	# List Page that enumerates all articles contained on the site that are
	# not future dated. If only future dated articles exist then return
	# a 404 error instead of the Index page
	count_of_present_articles = Article.objects.exclude(pub_date__gt=timezone.now()).count()
	try:
		context = {'all_articles':all_articles}
		if count_of_present_articles == 0:
			raise Exception("No Recent Articles!")
	except Exception:
		raise Http404
	return render(request, 'g43exercise/index.html', context)
	
	
def detail(request, article_id):
	# Detail page that displays all the contents of a 
	# particular article not published for a future date.
	# If a future dated article is requested, return a 404 error instead
	article = get_object_or_404(Article.objects.filter(pub_date__lte=timezone.now()), pk=article_id)
	context = {'all_articles': all_articles, 'article': article}
	return render(request, 'g43exercise/article.html', context)	
	

g43exercise/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
{% block htmladdon %}{% endblock %}
<html lang="en">
	{% block head %}
	{% block meta %}
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% endblock %}
	<title>{% block title %}G43 Tech Exercise{% endblock %}</title>
	{% block style %}
	<link rel="stylesheet" href={% static 'g43exercise/css/style.css' %}/>
	<link rel="stylesheet" href={% static 'g43exercise/css/bootstrap.min.css' %}/>
	{% endblock %}
	{% endblock %}
</head>
<body>
	{% block body %}
	<div class="container">
		{% block nav %}
		{% include "nav_side.html" %}
		{% endblock %}
		{% block main %}
		{% endblock %}
		{% block footer %}
		{% include "nav_toread.html" %}
		{% endblock %}
	</div>		
	{% block bodyjs %}
	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
	<!-- Include all compiled plugins (below), or include individual files as needed -->
	<script src="js/bootstrap.min.js"></script>		
	{% endblock %}
	{% endblock %}
</body>
</html>

g43exercise/templates/g43exercise/article.html
{% extends "base.html" %}
{% block title %}G43 Tech Exercise | {{article.title}}{% endblock %}
{% block main %}
	<main class="main col-xs-12 col-sm-10" role="primary">
		<article class="article full">
		{% if article %}
			<header>
				<h1 class="article-title">{{article.title}}</h1>
				<div class="pub-group">
					<div class="pubdate">{{article.pub_date|date:"l, F j, Y"}}</div>
					<div class="author"><a href="#">{{article.author}}</a></div>
				</div>
			</header>
			<section>
				<div class="hero-img"><img src="{% url 'g43:media' article.hero_image %}" alt="hero_img"/></div>
				<div class="full article-body">{{article.body_text|linebreaks}}</div>
				<div class="extra-img"><img src="{% url 'g43:media' article.optional_image %}"/></div>
			</section>
		{% else %}
			<header>
				<h1 class="article-title">Article Title</h1>
				<div class="pub-group">
					<div class="pubdate">Published: Date</div>
					<div class="author"><a href="#">Author Name</a></div>
				</div>
			</header>
			<section>
				<div class="hero-img"><img src="" alt="hero_img"/></div>
				<div class="full article-body">Article Body</div>
				<div class="extra-img"><img src="" alt="extra_img"/></div>
			</section>		
		{% endif %}
		</article>
	</main>
{% endblock %}

g43exercise/templates/g43exercise/index.html
{% extends "base.html" %}
{% load random_article %}
{% block main %}
	<main class="main col-xs-12 col-sm-10" role="primary">
		<article class="article preview">
		{% get_random_article as article_preview %}
		{% if article_preview %}
			<header>
				<h1 class="article-title">{{ article_preview.title }}</h1>
				<div class="pub-group">
					<div class="pubdate">{{article_preview.pub_date|date:"l, F j, Y"}}</div>
					<div class="author"><a href="#">{{ article_preview.author }}</a></div>
				</div>
			</header>
			<section>
				<div class="hero-img"><img src="{% url 'g43:media' article_preview.hero_image %}" alt="hero_img"/></div>
				<p class="article-body">{{ article_preview.body_text|truncatewords:150 }}  <a href="{% url 'g43:detail' article_preview.article_id %}" class="article-link">Read More</a></p>
			</section>
		{% else %}			
			<header>
				<h1 class="article-title">Article Title</h1>
				<div class="pub-group">
					<div class="pubdate">Published: Date</div>
					<div class="author"><a href="#">Author Name</a></div>
				</div>
			</header>
			<section>
				<div class="hero-img"><img src="" alt="hero_img"/></div>
				<p class="article-body">Article Body  <a href="#" class="article-link">Read More</a></p>
			</section>
		{% endif %}
		</article>
		<div class="top-articles">
			<ol class="article-list">
			{% if all_articles %}
				{% for article in all_articles %}
				<li>
					<h2 class="article-title">{{article.title}}</h2>
					<div class="article-body">{{article.body_text|truncatewords:50}}</div>
					<a href="{% url 'g43:detail' article.article_id %}" class="article-link">Call to Action</a>
				</li>
				{% endfor %}	
			{% else %}
				<li>
					<h2 class="article-title">List Title One</h2>
					<div class="article-body">Article Body 1</div>
					<a href="" class="article-link">Call to Action</a>
				</li>
				<li>
					<h2 class="article-title">List Title Two</h2>
					<div class="article-body">Article Body 2</div>
					<a href="" class="article-link">Call to Action</a>
				</li>
				<li>
					<h2 class="article-title">List Title Three</h2>
					<div class="article-body">Article Body 3</div>
					<a href="" class="article-link">Call to Action</a>
				</li>				
			{% endif %}
			</ol>
		</div>
	</main>
{% endblock %}

g43exercise/templates/nav_side.html
	<nav id="sidebar" class="nav col-xs-12 col-sm-2" role="navigation">		
		<div class="site-icon"></div>
		<div class="nav-group">
			<a href="{% url 'g43:index' %}"><div class="menu-icon"></div></a>
			<div class="search-icon"></div>
		</div>
		<ul class="nav-links">
		{% if not all_articles %}
			{% for article in all_articles %}
			<li>
				<a href="{% url 'g43:detail' article.article_id %}">
					<div class="nav-img"></div>
					{{article.title}}
				</a>
			</li>
			{% endfor %}	
		{% else %}
			<li><a href="#"><div class="nav-img"></div>Nav 1</a></li>
			<li><a href="#"><div class="nav-img"></div>Nav 2</a></li>
			<li><a href="#"><div class="nav-img"></div>Nav 3</a></li>
			<li><a href="#"><div class="nav-img"></div>Nav 4</a></li>
			<li><a href="#"><div class="nav-img"></div>Nav 5</a></li>
		{% endif %}			
		</ul>
	</nav>

g43exercise/templates/nav_toread.html
{% load random_article %}
	<span class="col-sm-2"></span>
	<footer class="footer" class="col-sm-10">
		<div class="read-next">
			<h2>What to Read Next</h2>
			<div id="arrows">
				<a href="#">&lt;</a><span class="bar">|</span><a href="#">&gt;</a>
			</div>
		</div>
		<ul id="read-next-links" class="nav-footer-links">
		{% get_random_article_list 4 as article_set %}
		{% if article_set %}
			{% for article in article_set %}
			<li>
				<a href="{% url 'g43:detail' article.article_id %}" class="thumb">
					<div class="thumb-img"><img src="{% url 'g43:media' article.hero_image %}"/></div>
					{{article.title|truncatechars:18}}
				</a>
			</li>
			{% endfor %}	
		{% else %}
			<li><a href="" class="thumb"><div class="thumb-img"><img src="" alt="thumb"/></div>Related Title 1</a></li>
			<li><a href="" class="thumb"><div class="thumb-img"><img src="" alt="thumb"/></div>Related Title 2</a></li>
			<li><a href="" class="thumb"><div class="thumb-img"><img src="" alt="thumb"/></div>Related Title 3</a></li>
			<li><a href="" class="thumb"><div class="thumb-img"><img src="" alt="thumb"/></div>Related Title 4</a></li>
		{% endif %}			
		</ul>
	</footer>